version: "3"

services:
  front:
    build: .
    ports:
      - 80:80
    networks:
      - services
    restart: on-failure
    depends_on:
      - back

  back:
    build: ./src
    ports:
      - 3001:3001
    networks:
      - services
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    build: ./docker-mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
      - configdb:/data/configdb
    networks:
      - services
    restart: on-failure

networks:
  services: {}

volumes:
  db: {}
  configdb: {}