version: "3"

services:
  proxy:
    build: ./proxy
    ports:
      - ${PROXYPORT}:${PROXYPORT}
    environment:
      - PORT=${PROXYPORT}
      - FRONTPORT=${FRONTPORT}
      - APIPORT=${APIPORT}
    networks:
      - services
    restart: on-failure
    depends_on:
      - front
      - back

  front:
    build: .
    ports:
      - ${FRONTPORT}:${FRONTPORT}
    environment:
      - PORT=${FRONTPORT}
    volumes:
      - ./build/:/var/www/build/:ro
    networks:
      - services
    restart: on-failure
    depends_on:
      - back

  back:
    build: ./src
    ports:
      - ${APIPORT}:${APIPORT}
    environment:
      - PORT=${APIPORT}
      - MONGOPORT=${MONGOPORT}
    volumes:
      - ./src/server/:/var/www/server/
    networks:
      - services
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    build: ./docker-mongo
    ports:
      - ${MONGOPORT}:${MONGOPORT}
    environment:
      - PORT=${MONGOPORT}
    volumes:
      - db:/data/db
      - configdb:/data/configdb
    networks:
      - services
    restart: on-failure

networks:
  services: {}

volumes:
  db: {}
  configdb: {}