version: "3"

services:
  mongodb:
    image: goodparents_mongodb
    ports:
      - 27017:27017
    environment:
      - PORT=27017
    volumes:
      - db:/data/db
      - configdb:/data/configdb
    networks:
      - services
    restart: on-failure

networks:
  services: {}

volumes:
  db: {}
  configdb: {}